/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_tevs_openbm_GatewayNative */

#ifndef _Included_eu_tevs_openbm_GatewayNative
#define _Included_eu_tevs_openbm_GatewayNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_tevs_openbm_GatewayNative
 * Method:    run
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_tevs_openbm_GatewayNative_run
  (JNIEnv *, jobject);

/*
 * Class:     eu_tevs_openbm_GatewayNative
 * Method:    setOnReceiveCallback
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_eu_tevs_openbm_GatewayNative_setOnReceiveCallback
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     eu_tevs_openbm_GatewayNative
 * Method:    connect
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_eu_tevs_openbm_GatewayNative_connect
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     eu_tevs_openbm_GatewayNative
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_eu_tevs_openbm_GatewayNative_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     eu_tevs_openbm_GatewayNative
 * Method:    send
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_eu_tevs_openbm_GatewayNative_send
  (JNIEnv *, jobject, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
